version: '3.8'
services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
nginx:
    image: nginx:alpine
    container_name: fastapi_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
